### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by sgtRoberty** [computations/lagrange-ng#1]
Dear authors,

**Machine**: Ubuntu 20.04.4

Hello! I'm currently having some difficulties building Lagrange-ng on my terminal. After `git clone` the repo, I issued the `make` command and the building started. However, I tried several times and it always stopped early and gave this error: 
![image](https://user-images.githubusercontent.com/101582763/168262524-f40192aa-b71f-4188-a773-1c1cd17be346.png)

The debug file is attached here:
[lagrange_error_debug.log](https://github.com/computations/lagrange-ng/files/8686142/lagrange_error_debug.log)

Could you please have a quick look into this issue? Any response will be much appreciated. Cheers!

Best regards,
Robert

**Comment by computations** [comment]
Thanks for the ticket. It seems I made a mistake when improving the code quality of the tool. I just pushed an update which should fix the problem!

**Comment by computations** [comment]
did this fix the problem? If it did, then I can close this ticket. Thanks!

**Comment by sgtRoberty** [comment]
Hi! Sorry for not replying to you sooner - yes! lagrange-ng was successfully built. Thank you for sorting this out!

**Comment by computations** [comment]
No problem! thanks for reporting the issue!
